// Auto-generated by generate-build-info.sh — do not edit manually.
// This file is tracked in git so the app always compiles, but the commit hash
// gets updated before each build to embed the current HEAD.
enum BuildInfo {
  static let builtCommit = "6bddc4a6b424a4498dc21cd3531130867d8e4331"
}
