#!/bin/bash
# Generates BuildInfo.generated.swift with the current git commit hash.
# Run this before `swift build` or add it as an Xcode Build Phase.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="$REPO_DIR/Sources/LobsDashboard/BuildInfo.generated.swift"

COMMIT=$(git -C "$REPO_DIR" rev-parse HEAD 2>/dev/null || echo "unknown")

cat > "$OUTPUT" << EOF
// Auto-generated by generate-build-info.sh — do not edit manually.
// This file is tracked in git so the app always compiles, but the commit hash
// gets updated before each build to embed the current HEAD.
enum BuildInfo {
  static let builtCommit = "$COMMIT"
}
EOF

echo "[build-info] Embedded commit: $COMMIT"
